import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { JavaScriptPropositionalLaboratoryFormatGeneratedModule, JavaScriptPropositionalLaboratoryFormatGeneratedSharedModule } from './generated/module.js';
import { JavaScriptPropositionalLaboratoryFormatValidator, registerValidationChecks } from './java-script-propositional-laboratory-format-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type JavaScriptPropositionalLaboratoryFormatAddedServices = {
    validation: {
        JavaScriptPropositionalLaboratoryFormatValidator: JavaScriptPropositionalLaboratoryFormatValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type JavaScriptPropositionalLaboratoryFormatServices = LangiumServices & JavaScriptPropositionalLaboratoryFormatAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const JavaScriptPropositionalLaboratoryFormatModule: Module<JavaScriptPropositionalLaboratoryFormatServices, PartialLangiumServices & JavaScriptPropositionalLaboratoryFormatAddedServices> = {
    validation: {
        JavaScriptPropositionalLaboratoryFormatValidator: () => new JavaScriptPropositionalLaboratoryFormatValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createJavaScriptPropositionalLaboratoryFormatServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    JavaScriptPropositionalLaboratoryFormat: JavaScriptPropositionalLaboratoryFormatServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        JavaScriptPropositionalLaboratoryFormatGeneratedSharedModule
    );
    const JavaScriptPropositionalLaboratoryFormat = inject(
        createDefaultModule({ shared }),
        JavaScriptPropositionalLaboratoryFormatGeneratedModule,
        JavaScriptPropositionalLaboratoryFormatModule
    );
    shared.ServiceRegistry.register(JavaScriptPropositionalLaboratoryFormat);
    registerValidationChecks(JavaScriptPropositionalLaboratoryFormat);
    return { shared, JavaScriptPropositionalLaboratoryFormat };
}
